services:
  postgres:
    image: postgres:17
    container_name: course-service-postgres
    environment:
      POSTGRES_DB: course_service_s4e
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: