spring:
  profiles:
    active: default
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest