spring:
  profiles:
    active: default
  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true

logging:
  level:
    com.study4ever.authservice.filter: DEBUG