server:
  port: ${EUREKA_SERVER_PORT:8761}

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
