spring:
  profiles:
    active: default
  application:
    name: progress-service
  
  config:
    import: optional:configserver:http://localhost:8888
  
  cloud:
    config:
      fail-fast: true

app:
  course-service:
    url: ${COURSE_SERVICE_URL:http://localhost:8082}

#logging:
#  level:
#    root: debug
#    sun.rmi.transport.tcp: WARN
#    sun.rmi.loader: WARN
#    javax.management.remote.rmi: WARN