spring:
  profiles:
    active: default
  application:
    name: progress-service
  
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
  
  cloud:
    config:
      fail-fast: true

#logging:
#  level:
#    root: debug
#    sun.rmi.transport.tcp: WARN
#    sun.rmi.loader: WARN
#    javax.management.remote.rmi: WARN