server:
  port: ${API_GATEWAY_PORT:8095}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
    loadbalancer:
      cache:
        ttl: 5s
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

security:
  jwt:
    secret-key: ${JWT_SECRET}
