server:
  port: 8095

spring:

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: course-service-read
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**,/api/v1/modules/**,/api/v1/lessons/**,/api/v1/tags/**
            - Method=GET
          filters:
            - name: JwtAuthentication
              args:
                allowedRoles:
                  - ROLE_TRAINEE
                  - ROLE_INSTRUCTOR
                  - ROLE_ADMIN

        - id: course-service-write
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/v1/courses/**,/api/v1/modules/**,/api/v1/lessons/**,/api/v1/tags/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - name: JwtAuthentication
              args:
                allowedRoles:
                  - ROLE_INSTRUCTOR
                  - ROLE_ADMIN

        - id: auth-service-admin
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - name: JwtAuthentication
              args:
                allowedRoles:
                  - ROLE_ADMIN

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret-key: ${JWT_SECRET}