server:
  port: 8081

spring:
  datasource:
    username: ${AUTH_DB_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${AUTH_DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION:900000}  # 15 minutes
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days
    issuer: study4ever-auth-service