server:
  port: 0

spring:
  datasource:
    url: jdbc:tc:postgresql:14:///course_service_test
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${embedded.rabbitmq.host}
    port: ${embedded.rabbitmq.port}
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 100
          max-attempts: 3
          max-interval: 1000
          multiplier: 1.5

retry:
  maxAttempts: 3
  initialDelay: 100
  multiplier: 1.5
  maxDelay: 1000

eureka:
  client:
    enabled: false