spring:
  datasource:
    url: ${COURSE_DB_URL}
  rabbitmq:
    host: rabbitmq
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
  cloud:
    config:
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
