server:
  port: 8081

spring:
  datasource:
    username: ${COURSE_DB_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${COURSE_DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Retry configuration for @Retryable annotation
retry:
  maxAttempts: 3
  initialDelay: 1000
  multiplier: 2
  maxDelay: 10000