server:
  port: ${COURSE_SERVICE_PORT:0}

spring:
  datasource:
    username: ${COURSE_DB_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${COURSE_DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

  cache:
    type: caffeine
    cache-names: activeSessions, userSessions
    caffeine:
      spec: maximumSize=500,expireAfterAccess=30m

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Retry configuration for @Retryable annotation
retry:
  maxAttempts: 3
  initialDelay: 1000
  multiplier: 2
  maxDelay: 10000

# RabbitMQ Configurations
rabbitmq:
  exchanges:
    events: study4ever.events.exchange
    study-sessions: study4ever.study-sessions.exchange
  queues:
    study-session-started: study.session.started.queue
    study-session-ended: study.session.ended.queue
    study-session-heartbeat: study.session.heartbeat.queue
    study-session-confirmation: study.session.confirmation.queue
  routing-keys:
    study-session-confirmation: study4ever.study-sessions.confirmation
    study-session-started: study.session.started
    study-session-ended: study.session.ended
    study-session-heartbeat: study.session.heartbeat

# Study Session Configuration
study-session:
  heartbeat-interval-seconds: 30
  max-inactivity-minutes: 15
  max-session-duration-minutes: 240
  session-check-interval-seconds: 60
  allow-multiple-active-sessions: false