server:
  port: ${COURSE_SERVICE_PORT:0}

spring:
  datasource:
    username: ${COURSE_DB_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${COURSE_DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Retry configuration for @Retryable annotation
retry:
  maxAttempts: 3
  initialDelay: 1000
  multiplier: 2
  maxDelay: 10000

# RabbitMQ Configurations
rabbitmq:
  exchanges:
    events: study4ever.events.exchange
    study-sessions: study4ever.study-sessions.exchange
  queues:
    study-session-started: study4ever.course.study-session-started.queue
    study-session-ended: study4ever.course.study-session-ended.queue
    study-session-heartbeat: study4ever.course.study-session-heartbeat.queue
  routing-keys:
    study-session-started: study4ever.study-sessions.started
    study-session-ended: study4ever.study-sessions.ended
    study-session-heartbeat: study4ever.study-sessions.heartbeat