server:
  port: 8095

spring:
  profiles:
    active: default
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

logging:
  level:
    com.study4ever.apigateway.filter: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret-key: ${JWT_SECRET}